"""Repository ports for the Sources context."""

from typing import Protocol
from uuid import UUID

from forge.adapters.persistence.models.sources import Category, Source


class SourcesRepository(Protocol):
    async def list_sources(self, user_id: UUID) -> list[Source]: ...
    async def get_source(self, user_id: UUID, source_id: UUID) -> Source | None: ...
    async def add_source(self, source: Source) -> Source: ...
    async def delete_source(self, source: Source) -> None: ...
    async def list_enabled_sources(self, user_id: UUID) -> list[Source]: ...

    async def list_categories(self, user_id: UUID) -> list[Category]: ...
    async def get_category(self, user_id: UUID, category_id: UUID) -> Category | None: ...
    async def add_category(self, category: Category) -> Category: ...
    async def delete_category(self, category: Category) -> None: ...
    async def category_name_exists(self, user_id: UUID, name: str) -> bool: ...
